### ISSUE TITLE
(feature suggestion) Migrate to Webpack (from Browserify)

### ISSUE THREAD

**Issue by raibutera** [mcfly-io/generator-mcfly#154]
## Intro 
generator-angular-famous-ionic has been fantastic for developing my ionic app. However, on more than one occasion I've found browserify to be the source of stress (shimming required for non-commonJS libraries, slow compile time). I've noticed a trend amongst web devs to move to Webpack. I think it may be a good time to migrate this generator across.

### Useful Links 
- [About Webpack (+ Why another Module Builder?)](http://webpack.github.io/docs/what-is-webpack.html)
- [Webpack Motivation](http://webpack.github.io/docs/what-is-webpack.html)

### Key Advantages for generator-angular-famous-ionic
- **Supports CommonJS syntax** 
    + minimal (maybe no?) changes required to generated app code
- Supports *AMD module syntax* out of the box (no shimming!)
- Supports *ES6 style syntax*
- Has **_loaders_** (like browserify transforms):
    + **typescript** and **ECMAScript 6** (via babel) loaders exist 
        * future proofing for Angular 2.0 
* Supports [**code splitting**](http://webpack.github.io/docs/code-splitting.html) !!!
* (AFAIK) is more performant than browserify (both in compilation and runtime)
- Has a [built in development server](http://webpack.github.io/docs/webpack-dev-server.html) (maybe no more need for browsersync?)
- Has great documentation (including a guide ["Webpack for Browserify Users"](http://webpack.github.io/docs/webpack-for-browserify-users.html))

What do the maintainers/contributors think about this transition? What would need to be done to do this?

**Comment by thaiat** [comment]
that's a good suggestion, but will require some amount of work as we will need need to support for both browserify and webpack

let see who is asking for that feature, and who is willing to start a PR

**Comment by thejameskyle** [comment]
Hi Babel contributor here. If you have any questions about babel or [babel-loader](https://github.com/babel/babel-loader) for webpack let me know or hop into our support chat: http://gitter.im/babel/babel

**Comment by thaiat** [comment]
@thejameskyle i will probably release the webpack support later this week.
everything is working fine right now except for a small issue: when I use the babel-loader along with source map, the source code for a file using es6 syntax is different from the original. I see some polyfills calls for example
this does not happen with babelify and browserify...

**Comment by thejameskyle** [comment]
I'm not sure, sourcemaps in `babelify` and `babel-loader` are created the same way, just handed off differently. Could you share an example of incorrect behavior?

**Comment by thaiat** [comment]
@thejameskyle 
I put together a minimalist repo to reproduce the issue: https://github.com/thaiat/webpack-babel-sourcemap. Steps to reproduce are in the README.

Bottom line is that `babel-loader` **has to be the first loader**. If not it will pollute the source maps

Let me know what you think
