### ISSUE TITLE
prod sourcemaps hosted on a local server

### ISSUE THREAD

**Issue by jskrzypek** [mcfly-io/generator-mcfly#213]
It would be nice to serve the production source maps on a local server and still be able to have them work with Sentry or other 3rd party error trackers.

Sentry needs the sourcemaps' links in the bundle.js files to point to an absolute URL, but perhaps this would work with `http://localhost:5000/...` meaning that browsersync could be tasked with hosting the sourcemaps and they would still render correctly in chrome.

**Comment by thaiat** [comment]
implemented in generator-sublime
