### ISSUE TITLE
Turn .sh's to shelljs

### ISSUE THREAD

**Issue by cyrilchapon** [mcfly-io/generator-mcfly#216]
Turning `./bin/*.sh`'s scripts to [shelljs](https://github.com/arturadib/shelljs) scripts will be something reasonable to make the installation Windows-compliant, wouldn't it ?

Not an expert of thoses scripts, that's a pure suggestion =)

**Comment by thaiat** [comment]
from what i know this runs fine on windows.
do you have any issue with it ?

**Comment by cyrilchapon** [comment]
Hey @thaiat 

Haven't tested that beautiful module, but digging through issues and stuff, I found that Windows support is garanteed only with manually `npm install -g` tools, whereas *linux* & *OSX* have some `./bin/*.sh` helpers. That's still the case, isn't it ?

**Comment by thaiat** [comment]
@cyrilchapon i use the generator on windows half the time and everything works fine
closing this for the moment, feel free to reopen if you have any issue.

and don't forget to try it out ;)
