### ISSUE TITLE
protractor-html-screenshot-reporter is not compatible with jasmine 2

### ISSUE THREAD

**Issue by jercoh** [mcfly-io/generator-mcfly#218]
`protractor-html-screenshot-reporter` is not compatible with jasmine 2. Maybe should you add a dependency to `protractor-jasmine2-screenshot-reporter` and modify the `protractor.conf.js`?

**Comment by thaiat** [comment]
hey @jercoh looks like a good candidate for a PR, what do you think?
even if you don t feel writing the whole PR by yourself it will surely help if you can write the install instructions with correct packages names and versions

**Comment by jercoh** [comment]
See: https://github.com/mcfly-io/generator-sublime/pull/234 and https://github.com/mcfly-io/generator-mcfly/pull/219

**Comment by jskrzypek** [comment]
@jercoh, a couple things: first I commented [here](https://github.com/mcfly-io/generator-mcfly/pull/219#issuecomment-116276986) with how you should modify your commits to help us keep our changelogs readable. 

Second I noticed in your PRs that you take a different strategy to fixing the issue from the one you suggest above. Can you please describe here in the issue what you chose to do and why? It would be a huge help for us to understand and accept your fixes. Thanks!

**Comment by jercoh** [comment]
@jskrzypek I realized that `protractor-jasmine2-screenshot-reporter` wasn't a better choice (it wasn't taking any screenshots see https://github.com/mlison/protractor-jasmine2-screenshot-reporter/issues/10).
So an other solutions was to switch to Jasmine 1 in the protractor configuration file, but `jasmine-spec-reporter` >2.x is compatible with Jasmine 2 only.
Hence this commit: https://github.com/jercoh/generator-sublime/commit/3f0cb9615edd15e4249790a405691ce4d9b6d0ef

**Comment by jskrzypek** [comment]
Awesome, thanks for that! We'll look at what we lose & gain by downgrading to jasmine 1.

**Comment by jskrzypek** [comment]
@jercoh, do you think you can check out the workarounds mentioned here https://github.com/jintoppy/protractor-html-screenshot-reporter/issues/44
on mping's fork of `protractor-html-screenshot-reporter`? Does the fork fix the issue with using Jasmine 2? I'm happy to help if you want to work with someone on these things.

I have a feeling it's better to patch/replace the reporter if possible rather than downgrade Jasmine. I'm worried the various syntax and other changes between versions 1 & 2 may break people's tests.

**Comment by jskrzypek** [comment]
Also if you don't have time today I can take a crack at it.

**Comment by jercoh** [comment]
@jskrzypek This fork seems to be working! If you don't mind having a dependency to a fork, I can commit the changes.

**Comment by Ramitmoni** [comment]
@jercoh  I tried the above code implementation however i do not see the reports and the screenshot in the baseDirectory specified ?

**Comment by Ramitmoni** [comment]
I tried using protractor-beautiful-reporter and it worked !!!
