### ISSUE TITLE
issues adding bower component.

### ISSUE THREAD

**Issue by digitalhobo** [mcfly-io/generator-mcfly#228]
I am trying to add parse angular patch bower component as a dependancy module to my app.

I included    
"parse-angular-patch": "./bower_components/parse-angular-patch/dist/parse-angular.js"
path to the package.json file and 
require('parse-angular-patch');
plus included the module name 'parse-angular' to my app module
but i am getting a Module 'parse-angular' is not available!

Am I missing something.

Thanks in advance.

**Comment by jskrzypek** [comment]
Is there a specific reason you are getting it from bower? It looks like is available from npm; if you use that version you don't need a browser entry.

**Comment by digitalhobo** [comment]
Super, thanks, that seems to work, However, if I try what i usually do, when I have done it with a yo angular generator
       "Parse.initialize(xxxxx,xxxxx);"
in the run injection, I get Parse is not defined.:0(

But thanks you for your help:0)

**Comment by thaiat** [comment]
can you create a repo for reproducing the issue ?

**Comment by thaiat** [comment]
you need to require Parse and put it as a global object on window

**Comment by digitalhobo** [comment]
sure it at this link
https://github.com/digitalhobo/bert

**Comment by thaiat** [comment]
can you make me a contributor of the repo?

**Comment by thaiat** [comment]
the fix is simple:
you need to add the following shim above "parse-angular-patch":
```json
"parse": {
      "exports": "Parse"
},
```

**Comment by digitalhobo** [comment]
Thats Great, Works fine.
Thanks for taking the time out to look at it Guys, Great help. Very much appreciated. 
:0)

**Comment by thaiat** [comment]
just out of curiosity, what are you building with the generator ?

**Comment by digitalhobo** [comment]
I am building a personal trainer tool. We have developed hardware that attaches to gym equipment and is able to track users workouts and display their progress in realtime.
You can have a look at the screen shots at the links below.

https://drive.google.com/file/d/0B8FfM2PtJR7JQWZQdV9PSkVabHM/view?usp=sharing

https://drive.google.com/file/d/0B8FfM2PtJR7JbVJJRUV2bTEtdVE/view?usp=sharing

:0)

**Comment by thaiat** [comment]
Nice work
was the generator helpfull? what other features would you like?

**Comment by digitalhobo** [comment]
Thanks - Yes, I think it is very helpful.
I think the performance seems to be better than using the ionic way. 
It might be good when we add a bower component, their is a way to automatically include the tags in package.js. But I understand why this has to be a manual thing. Also, in your documentation, you mention in 
"Adding a third party bower package"
"modify package.json bower section to include a path ....."
Should it be 
"modify package.json BROWSER section to include a path....."
And maybe mention adding the dependancies and exports to browserify-shim. 
Apart from that, I think its seamless. 
Thanks Havi :0)

**Comment by thaiat** [comment]
noted, i will fix the doc

**Comment by jskrzypek** [comment]
Thanks for catching that :smile:

**Comment by digitalhobo** [comment]
:+1:
