### ISSUE TITLE
Add documentation for debugging on remote devices

### ISSUE THREAD

**Issue by jancel** [mcfly-io/generator-mcfly#238]
Working with this framework, one pain point is bridging the gap for console logs between this generator, ionic and cordova.  I can't see the proper webview to do chrome debugging. Haven't dived into Apple, but this sort of thing is going to be necessary for people just starting to use this generator.

If I figure it out, I will post.

**Comment by thaiat** [comment]
hey @jancel, i didn't quite get your point... could you be a little more specific about what you are trying to do ?

**Comment by jancel** [comment]
Thanks.  Yes. I'm actually trying to run a pretty much boiler plate application on an an android device and view the console logs while doing so without dropping into the ionic, i.e. gulp cordova:run --platform android

**Comment by thaiat** [comment]
assuming your android device is connected with usb, you can debug your app opening chrome at the following url : `chrome://inspect`

**Comment by thaiat** [comment]
closing this for the moment feel free to reopen
