### ISSUE TITLE
Add option to prevent the rewrite of all modules imports in the main-*.js

### ISSUE THREAD

**Issue by ghaiat** [mcfly-io/generator-mcfly#246]
When you work with multiple targets and you create a new module, you dont want mcfly to automatically includes all modules for all projects....

**Comment by jskrzypek** [comment]
This is happening when you add a new module or a new target?

**Comment by ghaiat** [comment]
a new module, i didnt check for a new target

**Comment by jskrzypek** [comment]
Hmm, ok that makes sense... there might even be a flag to prevent the auto-injection already. I'm just looking at #245 so I'll take a look

**Comment by jskrzypek** [comment]
Ok I'm adding a `--skip-inject-modules` flag to `yo mcfly:target` and `yo mcfly:module`.

**Comment by ghaiat** [comment]
nice
