### ISSUE TITLE
Add support for bb10 resources

### ISSUE THREAD

**Issue by ghaiat** [mcfly-io/generator-mcfly#248]
add this to taskImageCordova

if (fs.existsSync(constants.dist.distFolder + '/platforms/blackberry10')) {
            gulp.src(constants.cordova.src + '/resources/blackberry10/**/*')
                .pipe(gulp.dest(constants.dist.distFolder + '/platforms/blackberry10/platform_www'));
        }

**Comment by thaiat** [comment]
changing the globs to `'/resources/blackberry10/**/*'` instead of  `'/resources/blackberry10/*/'`

**Comment by thaiat** [comment]
see https://github.com/mcfly-io/generator-sublime/pull/259
