### ISSUE TITLE
Update transform-loader to version 2.3

### ISSUE THREAD

**Issue by BraunreutherA** [mcfly-io/generator-mcfly#251]
When using node v4.1 the transform-loader module had a bug with buffer.copy - Updating it to version 2.3 fixed the bug.

**Comment by BraunreutherA** [comment]
Would make a PR but where is the template for the gulps-package.json located? Thanks

**Comment by jskrzypek** [comment]
It's in [mcfly-io/generator-sublime](https://github.com/mcfly-io/generator-sublime).

Yeoman doesn't let you touch the same file twice so there needs to be two generators.

**Comment by jskrzypek** [comment]
Happy to receive a PR :+1:
