### ISSUE TITLE
Error creating mobile-target

### ISSUE THREAD

**Issue by faboweb** [mcfly-io/generator-mcfly#267]
Hi I'm getting an error just creating the mobile-target:

C:\Entwicklung\Git\myapp>yo mcfly:target myapp --mobile
C:\Users\Me\AppData\Roaming\npm\node_modules\generator-mcfly\node_m
oman-generator\node_modules\mkdirp\index.js:90
                    throw err0;
                          ^
RangeError: Maximum call stack size exceeded
    at new Error (native)
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at sync (C:\Users\Me\AppData\Roaming\npm\node_modules\generator
de_modules\yeoman-generator\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\Me\AppData\Roaming\npm\node_modules\generator
de_modules\yeoman-generator\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\Me\AppData\Roaming\npm\node_modules\generator
de_modules\yeoman-generator\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Me\AppData\Roaming\npm\node_modules\generator
de_modules\yeoman-generator\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Me\AppData\Roaming\npm\node_modules\generator
de_modules\yeoman-generator\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Me\AppData\Roaming\npm\node_modules\generator
de_modules\yeoman-generator\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\Me\AppData\Roaming\npm\node_modules\generator
de_modules\yeoman-generator\node_modules\mkdirp\index.js:78:17)

**Comment by thaiat** [comment]
what version of the generator are u using?
what is your os ?

**Comment by faboweb** [comment]
Hi,
thanks for the quick reply. I'm using the newest version in windows 10.

**Comment by thaiat** [comment]
not sure what is your problem, try uninstall and reinstall the generator
and aslo i will need the full output

**Comment by faboweb** [comment]
i did an uninstall and reinstall and nothing changed
the output I provided is the full output

**Comment by thaiat** [comment]
is `mclfy:target` the first command you execute on a clean directory ?
because the first command should be `yo mcfly --mobile`

**Comment by jskrzypek** [comment]
Can you give us also  outputs of the following commands?

```sh
node --version
npm --version
npm list -g --depth=0
```
`

**Comment by jskrzypek** [comment]
Also can you investigate if this is related to https://github.com/substack/node-mkdirp/issues/70 ?

**Comment by thaiat** [comment]
ok, i found the issue, releasing a new version in a few minutes

**Comment by thaiat** [comment]
@faboweb new version 1.7.11 should fix your issue
can you let me know that this is working ?

**Comment by faboweb** [comment]
@thaiat perfect! it's working! thanks a lot!
