### ISSUE TITLE
Can't setup a new app

### ISSUE THREAD

**Issue by Qualinost1** [mcfly-io/generator-mcfly#275]
Hi,
I'm very new in Ionic/Famo.us world and even in the node.js world and I would like to use this generator but when I try the command 

`yo mcfly`

or 

`yo mcfly myIonicApp`

I got this return 

`(ERROR) It looks like you do not have python installed...`

I obviously installed Python 3.5.0 by downloading it here https://www.python.org/downloads/ (I'm on windows 10)

Here is what I actually did:

`npm install -g yo bower grunt-cli gulp`
`npm install -g generator-sublime`

and finaly

`npm install -g generator-mcfly`

What's wrong with this?

Thanks in advance for your help.

**Comment by thaiat** [comment]
you have to update your PATH variable with Python

**Comment by Qualinost1** [comment]
Yeah that's what I was checking just now. It's in my PATH

**Comment by thaiat** [comment]
if you open a new command prompt and type:
```bash
python
```

what do you get ?

**Comment by Qualinost1** [comment]
God, I just restarted my computer and everything seems good.. Damn Windows...

Sorry for this ridiculous Issues and thanks a lot for your help.

P.S: I would like to also thank you for your conference (https://www.youtube.com/watch?v=L56RnM6VI-w) which was very helpful for me to understand a lot of things, even more with your french accent (I'm french ;))

**Comment by thaiat** [comment]
hey hey merci :)
j ai abondonné depuis longtemps l idée d améliorer mon accent en anglais.. :smile: 

there are a few other confs that you might find useful:
https://www.youtube.com/watch?v=EgRh09CO_rk
https://www.youtube.com/watch?v=EEPzQLRsVQk

**Comment by Qualinost1** [comment]
Merci!
Le mien n'est pas meilleur, loin de là.

Thanks again for all this awesome work.

**Comment by thaiat** [comment]
oh and one last thing, i would recommend against trying to use famo.us, those guys have been unreliable to say the least, the framework is very difficult to use, and they've been quiet for the last couple of months

use ionic instead, not much difference in the end result, but a lot easier to use, and a clear roadmap

**Comment by Qualinost1** [comment]
Yeah that's what I'm targeting. 
I watched your conf because I'm curious on the famo.us ability to render animations on 60fps. But at this time, there's such a lack of out of the box components on my point of view.

I come from native Android dev background, and my first Ionic app is a bit disapointing in regards of the UI performances. Already looking forward for Angular 2.0 and Ionic updates for this.
