### ISSUE TITLE
wiki images 

### ISSUE THREAD

**Issue by totojab** [mcfly-io/generator-mcfly#297]
![mcfly-logo](https://cloud.githubusercontent.com/assets/6795299/11127201/badc47b2-897b-11e5-90cb-87bd61c4dc82.png)

**Comment by totojab** [comment]
![protractor-logo](https://cloud.githubusercontent.com/assets/6795299/11127305/68bb4590-897c-11e5-9ab9-4823c5591deb.png)

**Comment by totojab** [comment]
![protractor-logo](https://cloud.githubusercontent.com/assets/6795299/11127315/77fc9c02-897c-11e5-9026-b1159f9c71e6.png)

**Comment by totojab** [comment]
![hbcnu](https://cloud.githubusercontent.com/assets/6795299/11127361/b1a8309c-897c-11e5-96a4-e53357a9f9e2.png)

**Comment by totojab** [comment]
![1mc2kxh](https://cloud.githubusercontent.com/assets/6795299/11127418/e7f4798a-897c-11e5-9ccd-0e0f13810f64.jpg)

**Comment by totojab** [comment]
![capture d ecran 2015-11-12 a 20 39 00](https://cloud.githubusercontent.com/assets/6795299/11127533/71f856e2-897d-11e5-9231-86852bf20a92.png)

**Comment by thaiat** [comment]
what is it ?

**Comment by totojab** [comment]
![banner](https://cloud.githubusercontent.com/assets/6795299/11168863/ea662274-8baa-11e5-849e-806145a2b025.png)
