### ISSUE TITLE
Question: Problems when I use iCheck, how can i deal with the css file?

### ISSUE THREAD

**Issue by xuyukuan** [mcfly-io/generator-mcfly#300]
I use "npm install icheck" to involve icheck(https://github.com/fronteed/icheck) lib in my project.
but when I try to @import the css class in main.sass file. it doesn't work.
something like:
```
@import "../../node_modules/icheck/skins/all";
```
because all.css import sub css files from sub-directory.
they are not found in main.css.

so is there a solution for this kind of css file?

**Comment by thaiat** [comment]
import should work..
if it does not, i guess you will have to build yourself a bundle css for icheck

not related to the generator though
