### ISSUE TITLE
Prepublish doesnt install all dependencies

### ISSUE THREAD

**Issue by gbrennon** [mcfly-io/generator-mcfly#306]
Hey guys

I did run bin/prepublish.sh to install all dependencies but every task still fails because it needs to install some other packages like 'vinyl-source-stream'.

**Comment by thaiat** [comment]
prepublish does not do anything, the code is commented.
Why do you need to run prepublish and what do you think it is doing ?

**Comment by thaiat** [comment]
related to #313, should be fixed now
