### ISSUE TITLE
How to get production version?

### ISSUE THREAD

**Issue by AzureVoteWise** [mcfly-io/generator-mcfly#311]
How do I get a production version? I'm running `gulp dist`, which is "working" in the console, bit the only folder in dist/app is the dev folder.

**Comment by jskrzypek** [comment]
Sorry for the delayed reply, the answer is here: https://github.com/mcfly-io/generator-mcfly#cordova-applications

Basically you have to change the `dist` mode to `prod` using the `mode` flag 
```sh
gulp dist -m prod
# or
gulp dist --mode=prod
```
The default mode is `dev` because most of the time you're not building for prod.
